-- V20260129.1500__enforce_created_at_not_null.sql
-- 强化所有核心实体的 created_at 约束：非空且默认值为 CURRENT_TIMESTAMP

-- Edge 领域
ALTER TABLE edge_area ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE edge_area ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE edge ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE edge ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE edge_nic ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE edge_nic ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE edge_nic_ip ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE edge_nic_ip ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

-- EOP 领域
ALTER TABLE eop_product ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE eop_product ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE eop_service ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE eop_service ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE eop_app ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE eop_app ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE eop_bound ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE eop_bound ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE eop_port_occupation ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE eop_port_occupation ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE eop_transfer ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE eop_transfer ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
